export const FURNITURE_CATALOG = [
  // ── Bedroom ─────────────────────────────────────────────────────────────
  { type:'bed-twin',      label:'Twin Bed',        width:3,    depth:6.25, height3d:2,   color:'#7B6E5D', category:'Bedroom',      icon:'🛏', price:350  },
  { type:'bed-full',      label:'Full Bed',         width:4.5,  depth:6.25, height3d:2,   color:'#7B6E5D', category:'Bedroom',      icon:'🛏', price:500  },
  { type:'bed-queen',     label:'Queen Bed',        width:5,    depth:6.67, height3d:2,   color:'#7B6E5D', category:'Bedroom',      icon:'🛏', price:750  },
  { type:'bed-king',      label:'King Bed',         width:6.33, depth:6.67, height3d:2,   color:'#7B6E5D', category:'Bedroom',      icon:'🛏', price:1100 },
  { type:'bed-crib',      label:'Baby Crib',        width:2.5,  depth:5,    height3d:3,   color:'#C8B8A0', category:'Bedroom',      icon:'🛏', price:280  },
  { type:'bed-bunk',      label:'Bunk Bed',         width:3,    depth:6.5,  height3d:5,   color:'#8B7355', category:'Bedroom',      icon:'🛏', price:620  },
  { type:'nightstand',    label:'Nightstand',       width:1.5,  depth:1.5,  height3d:2.5, color:'#A08060', category:'Bedroom',      icon:'🟫', price:180  },
  { type:'dresser',       label:'Dresser',          width:3.5,  depth:1.5,  height3d:4,   color:'#A08060', category:'Bedroom',      icon:'🗄', price:350  },
  { type:'wardrobe',      label:'Wardrobe',         width:3,    depth:2,    height3d:7,   color:'#8B6A4A', category:'Bedroom',      icon:'🚪', price:450  },
  { type:'bench-foot',    label:'Foot Bench',       width:4,    depth:1.5,  height3d:1.5, color:'#8B7355', category:'Bedroom',      icon:'⬜', price:200  },
  // ── Living Room ──────────────────────────────────────────────────────────
  { type:'sofa-2',        label:'Sofa (2-seat)',    width:5,    depth:2.5,  height3d:3,   color:'#5B7A9A', category:'Living Room',  icon:'🛋', price:550  },
  { type:'sofa-3',        label:'Sofa (3-seat)',    width:7,    depth:2.5,  height3d:3,   color:'#5B7A9A', category:'Living Room',  icon:'🛋', price:800  },
  { type:'sofa-l',        label:'L-Sofa',           width:9,    depth:7,    height3d:3,   color:'#4A6A8A', category:'Living Room',  icon:'🛋', price:1200 },
  { type:'armchair',      label:'Armchair',         width:3,    depth:3,    height3d:3,   color:'#6A8BAA', category:'Living Room',  icon:'🪑', price:380  },
  { type:'coffee-table',  label:'Coffee Table',     width:4,    depth:2,    height3d:1.5, color:'#A08060', category:'Living Room',  icon:'⬜', price:280  },
  { type:'tv-stand',      label:'TV Stand',         width:5,    depth:1.5,  height3d:2,   color:'#555555', category:'Living Room',  icon:'📺', price:220  },
  { type:'bookshelf',     label:'Bookshelf',        width:3,    depth:1,    height3d:6,   color:'#8B7355', category:'Living Room',  icon:'📚', price:180  },
  { type:'side-table',    label:'Side Table',       width:1.5,  depth:1.5,  height3d:2,   color:'#A08060', category:'Living Room',  icon:'⬜', price:150  },
  { type:'ottoman',       label:'Ottoman',          width:3,    depth:3,    height3d:1.5, color:'#7A8A6A', category:'Living Room',  icon:'⬜', price:220  },
  // ── Dining ───────────────────────────────────────────────────────────────
  { type:'dining-4',      label:'Dining Table (4)', width:4,    depth:3,    height3d:2.5, color:'#A08060', category:'Dining',       icon:'🍽', price:400  },
  { type:'dining-6',      label:'Dining Table (6)', width:6,    depth:3,    height3d:2.5, color:'#A08060', category:'Dining',       icon:'🍽', price:600  },
  { type:'dining-8',      label:'Dining Table (8)', width:8,    depth:3.5,  height3d:2.5, color:'#A08060', category:'Dining',       icon:'🍽', price:800  },
  { type:'dining-chair',  label:'Dining Chair',     width:1.5,  depth:1.5,  height3d:3,   color:'#8B7355', category:'Dining',       icon:'🪑', price:120  },
  { type:'bar-stool',     label:'Bar Stool',        width:1.5,  depth:1.5,  height3d:3.5, color:'#888888', category:'Dining',       icon:'🪑', price:90   },
  // ── Kitchen ───────────────────────────────────────────────────────────────
  { type:'fridge',        label:'Refrigerator',     width:3,    depth:2.5,  height3d:6,   color:'#CCCCCC', category:'Kitchen',      icon:'🧊', price:900  },
  { type:'stove',         label:'Stove',            width:2.5,  depth:2,    height3d:3,   color:'#888888', category:'Kitchen',      icon:'🍳', price:700  },
  { type:'counter',       label:'Counter',          width:4,    depth:2,    height3d:3,   color:'#D8CCBF', category:'Kitchen',      icon:'⬜', price:400  },
  { type:'kitchen-island',label:'Kitchen Island',   width:4,    depth:2.5,  height3d:3,   color:'#C0B090', category:'Kitchen',      icon:'⬛', price:600  },
  { type:'dishwasher',    label:'Dishwasher',       width:2,    depth:2,    height3d:3,   color:'#AAAAAA', category:'Kitchen',      icon:'🍽', price:650  },
  { type:'microwave',     label:'Microwave',        width:1.5,  depth:1,    height3d:1.5, color:'#999999', category:'Kitchen',      icon:'📦', price:180  },
  { type:'washer',        label:'Washing Machine',  width:2,    depth:2.5,  height3d:3,   color:'#DDDDDD', category:'Kitchen',      icon:'🌀', price:580  },
  { type:'dryer',         label:'Dryer',            width:2,    depth:2.5,  height3d:3,   color:'#DDDDDD', category:'Kitchen',      icon:'🌀', price:540  },
  // ── Bathroom ─────────────────────────────────────────────────────────────
  { type:'bathtub',       label:'Bathtub',          width:5,    depth:2.5,  height3d:1.5, color:'#A8C8E0', category:'Bathroom',     icon:'🛁', price:500  },
  { type:'toilet',        label:'Toilet',           width:1.5,  depth:2.5,  height3d:2.5, color:'#EEEEEE', category:'Bathroom',     icon:'🚽', price:280  },
  { type:'vanity',        label:'Vanity',           width:3,    depth:1.5,  height3d:3,   color:'#CCCCCC', category:'Bathroom',     icon:'🪥', price:350  },
  { type:'shower',        label:'Shower Stall',     width:3,    depth:3,    height3d:7.5, color:'#B0D0E8', category:'Bathroom',     icon:'🚿', price:800  },
  // ── Office ────────────────────────────────────────────────────────────────
  { type:'desk',          label:'Desk',             width:4,    depth:2,    height3d:2.5, color:'#A08060', category:'Office',       icon:'🖥', price:320  },
  { type:'l-desk',        label:'L-Desk',           width:5,    depth:4,    height3d:2.5, color:'#A08060', category:'Office',       icon:'🖥', price:480  },
  { type:'office-chair',  label:'Office Chair',     width:2,    depth:2,    height3d:3.5, color:'#444444', category:'Office',       icon:'💺', price:250  },
  { type:'filing-cabinet',label:'Filing Cabinet',   width:1.5,  depth:2,    height3d:4,   color:'#888888', category:'Office',       icon:'🗄', price:180  },
  // ── Architecture ─────────────────────────────────────────────────────────
  { type:'door-single',   label:'Door (Single)',    width:3,    depth:0.5,  height3d:7,   color:'#8B6A4A', category:'Architecture', icon:'🚪', price:0    },
  { type:'door-double',   label:'Door (Double)',    width:5,    depth:0.5,  height3d:7,   color:'#8B6A4A', category:'Architecture', icon:'🚪', price:0    },
  { type:'window',        label:'Window',           width:4,    depth:0.25, height3d:4,   color:'#A8C8E0', category:'Architecture', icon:'🪟', price:0    },
  { type:'sliding-door',  label:'Sliding Door',     width:4,    depth:0.25, height3d:7,   color:'#8B6A4A', category:'Architecture', icon:'🚪', price:0    },
  { type:'stairs',        label:'Stairs',           width:4,    depth:8,    height3d:4,   color:'#B0A090', category:'Architecture', icon:'🪜', price:0    },
  { type:'arch',          label:'Archway',          width:3,    depth:0.5,  height3d:7,   color:'#C8B8A8', category:'Architecture', icon:'🏛', price:0    },
  // ── Decor & Lifestyle ─────────────────────────────────────────────────────
  { type:'rug-5x8',       label:'Rug (5×8)',        width:5,    depth:8,    height3d:0.1, color:'#8B7A6A', category:'Decor',        icon:'🟫', price:180  },
  { type:'rug-round',     label:'Round Rug (6ft)',  width:6,    depth:6,    height3d:0.1, color:'#7A8B6A', category:'Decor',        icon:'⭕', price:160  },
  { type:'plant-lg',      label:'Large Plant',      width:2,    depth:2,    height3d:4,   color:'#3A7A3A', category:'Decor',        icon:'🌿', price:80   },
  { type:'plant-sm',      label:'Small Plant',      width:1,    depth:1,    height3d:2,   color:'#3A7A3A', category:'Decor',        icon:'🌿', price:40   },
  { type:'floor-lamp',    label:'Floor Lamp',       width:1,    depth:1,    height3d:5,   color:'#C8C0A0', category:'Decor',        icon:'💡', price:120  },
  { type:'piano',         label:'Piano',            width:5,    depth:3,    height3d:3.5, color:'#1A1A1A', category:'Decor',        icon:'🎹', price:2500 },
  { type:'dog-bed',       label:'Pet Bed',          width:3,    depth:2,    height3d:0.5, color:'#8B7060', category:'Decor',        icon:'🐾', price:60   },
  // ── Fitness ───────────────────────────────────────────────────────────────
  { type:'treadmill',     label:'Treadmill',        width:3,    depth:6,    height3d:3,   color:'#444444', category:'Fitness',      icon:'🏃', price:800  },
  { type:'exercise-bike', label:'Exercise Bike',    width:2,    depth:4,    height3d:3.5, color:'#333333', category:'Fitness',      icon:'🚴', price:500  },
  { type:'yoga-mat',      label:'Yoga Mat',         width:2.5,  depth:6,    height3d:0.1, color:'#5A8A5A', category:'Fitness',      icon:'🧘', price:40   },
  { type:'weight-bench',  label:'Weight Bench',     width:2,    depth:5,    height3d:2,   color:'#555555', category:'Fitness',      icon:'💪', price:280  },
];
