export const FURNITURE_CATALOG = [
  { type: 'bed-twin',       label: 'Twin Bed',        width: 3,    depth: 6.25, height3d: 2,   color: '#7B6E5D', category: 'Bedroom',     icon: '🛏', price: 350  },
  { type: 'bed-full',       label: 'Full Bed',         width: 4.5,  depth: 6.25, height3d: 2,   color: '#7B6E5D', category: 'Bedroom',     icon: '🛏', price: 500  },
  { type: 'bed-queen',      label: 'Queen Bed',        width: 5,    depth: 6.67, height3d: 2,   color: '#7B6E5D', category: 'Bedroom',     icon: '🛏', price: 750  },
  { type: 'bed-king',       label: 'King Bed',         width: 6.33, depth: 6.67, height3d: 2,   color: '#7B6E5D', category: 'Bedroom',     icon: '🛏', price: 1100 },
  { type: 'nightstand',     label: 'Nightstand',       width: 1.5,  depth: 1.5,  height3d: 2.5, color: '#A08060', category: 'Bedroom',     icon: '🟫', price: 180  },
  { type: 'dresser',        label: 'Dresser',          width: 3.5,  depth: 1.5,  height3d: 4,   color: '#A08060', category: 'Bedroom',     icon: '🗄', price: 350  },
  { type: 'wardrobe',       label: 'Wardrobe',         width: 3,    depth: 2,    height3d: 7,   color: '#8B6A4A', category: 'Bedroom',     icon: '🚪', price: 450  },
  { type: 'sofa-2',         label: 'Sofa (2-seat)',    width: 5,    depth: 2.5,  height3d: 3,   color: '#5B7A9A', category: 'Living Room', icon: '🛋', price: 550  },
  { type: 'sofa-3',         label: 'Sofa (3-seat)',    width: 7,    depth: 2.5,  height3d: 3,   color: '#5B7A9A', category: 'Living Room', icon: '🛋', price: 800  },
  { type: 'sofa-l',         label: 'L-Sofa',           width: 9,    depth: 7,    height3d: 3,   color: '#4A6A8A', category: 'Living Room', icon: '🛋', price: 1200 },
  { type: 'armchair',       label: 'Armchair',         width: 3,    depth: 3,    height3d: 3,   color: '#6A8BAA', category: 'Living Room', icon: '🪑', price: 380  },
  { type: 'coffee-table',   label: 'Coffee Table',     width: 4,    depth: 2,    height3d: 1.5, color: '#A08060', category: 'Living Room', icon: '⬜', price: 280  },
  { type: 'tv-stand',       label: 'TV Stand',         width: 5,    depth: 1.5,  height3d: 2,   color: '#555555', category: 'Living Room', icon: '📺', price: 220  },
  { type: 'bookshelf',      label: 'Bookshelf',        width: 3,    depth: 1,    height3d: 6,   color: '#8B7355', category: 'Living Room', icon: '📚', price: 180  },
  { type: 'side-table',     label: 'Side Table',       width: 1.5,  depth: 1.5,  height3d: 2,   color: '#A08060', category: 'Living Room', icon: '⬜', price: 150  },
  { type: 'dining-4',       label: 'Dining Table (4)', width: 4,    depth: 3,    height3d: 2.5, color: '#A08060', category: 'Dining',      icon: '🍽', price: 400  },
  { type: 'dining-6',       label: 'Dining Table (6)', width: 6,    depth: 3,    height3d: 2.5, color: '#A08060', category: 'Dining',      icon: '🍽', price: 600  },
  { type: 'dining-8',       label: 'Dining Table (8)', width: 8,    depth: 3.5,  height3d: 2.5, color: '#A08060', category: 'Dining',      icon: '🍽', price: 800  },
  { type: 'dining-chair',   label: 'Dining Chair',     width: 1.5,  depth: 1.5,  height3d: 3,   color: '#8B7355', category: 'Dining',      icon: '🪑', price: 120  },
  { type: 'fridge',         label: 'Refrigerator',     width: 3,    depth: 2.5,  height3d: 6,   color: '#CCCCCC', category: 'Kitchen',     icon: '🧊', price: 900  },
  { type: 'stove',          label: 'Stove',            width: 2.5,  depth: 2,    height3d: 3,   color: '#888888', category: 'Kitchen',     icon: '🍳', price: 700  },
  { type: 'counter',        label: 'Counter',          width: 4,    depth: 2,    height3d: 3,   color: '#D8CCBF', category: 'Kitchen',     icon: '⬜', price: 400  },
  { type: 'kitchen-island', label: 'Kitchen Island',   width: 4,    depth: 2.5,  height3d: 3,   color: '#C0B090', category: 'Kitchen',     icon: '⬛', price: 600  },
  { type: 'dishwasher',     label: 'Dishwasher',       width: 2,    depth: 2,    height3d: 3,   color: '#AAAAAA', category: 'Kitchen',     icon: '🍽', price: 650  },
  { type: 'bathtub',        label: 'Bathtub',          width: 5,    depth: 2.5,  height3d: 1.5, color: '#A8C8E0', category: 'Bathroom',    icon: '🛁', price: 500  },
  { type: 'toilet',         label: 'Toilet',           width: 1.5,  depth: 2.5,  height3d: 2.5, color: '#EEEEEE', category: 'Bathroom',    icon: '🚽', price: 280  },
  { type: 'vanity',         label: 'Vanity',           width: 3,    depth: 1.5,  height3d: 3,   color: '#CCCCCC', category: 'Bathroom',    icon: '🪥', price: 350  },
  { type: 'shower',         label: 'Shower',           width: 3,    depth: 3,    height3d: 7.5, color: '#B0D0E8', category: 'Bathroom',    icon: '🚿', price: 800  },
  { type: 'desk',           label: 'Desk',             width: 4,    depth: 2,    height3d: 2.5, color: '#A08060', category: 'Office',      icon: '🖥', price: 320  },
  { type: 'l-desk',         label: 'L-Desk',           width: 5,    depth: 4,    height3d: 2.5, color: '#A08060', category: 'Office',      icon: '🖥', price: 480  },
  { type: 'office-chair',   label: 'Office Chair',     width: 2,    depth: 2,    height3d: 3.5, color: '#444444', category: 'Office',      icon: '💺', price: 250  },
  { type: 'filing-cabinet', label: 'Filing Cabinet',   width: 1.5,  depth: 2,    height3d: 4,   color: '#888888', category: 'Office',      icon: '🗄', price: 180  },
];
